# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1f1d2e"

# Main text color
theme[main_fg]="#e0dce8"

# Title color for boxes
theme[title]="#e0dce8"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#9ccfd8"

# Background color of selected item in processes box
theme[selected_bg]="#33304d"

# Foreground color of selected item in processes box
theme[selected_fg]="#9ccfd8"

# Color of inactive/disabled text
theme[inactive_fg]="#6e6a86"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#ea64a3"

# Background color of the percentage meters
theme[meter_bg]="#33304d"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ea64a3"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#c4a1d4"
theme[mem_box]="#a6d189"
theme[net_box]="#eb6f92"
theme[proc_box]="#9ccfd8"

# Box divider line and small boxes line color
theme[div_line]="#6e6a86"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#a6d189"
theme[temp_mid]="#f6c177"
theme[temp_end]="#eb6f92"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#9ccfd8"
theme[cpu_mid]="#9ccfd8"
theme[cpu_end]="#c4a1d4"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#c4a1d4"
theme[free_mid]="#c4a1d4"
theme[free_end]="#9ccfd8"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#9ccfd8"
theme[cached_mid]="#9ccfd8"
theme[cached_end]="#c4a1d4"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#f6c177"
theme[available_mid]="#eb6f92"
theme[available_end]="#eb6f92"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#a6d189"
theme[used_mid]="#a6d189"
theme[used_end]="#9ccfd8"

# Download graph colors (Peach -> Red)
theme[download_start]="#f6c177"
theme[download_mid]="#eb6f92"
theme[download_end]="#eb6f92"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#a6d189"
theme[upload_mid]="#a6d189"
theme[upload_end]="#9ccfd8"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#9ccfd8"
theme[process_mid]="#c4a1d4"
theme[process_end]="#c4a1d4"